In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [3]:
campaigns_df = pd.read_csv('data/campaigns.csv')
customers_df = pd.read_csv('data/customers.csv')
events_df = pd.read_csv('data/events.csv')
products_df = pd.read_csv('data/products.csv')
transactions_df = pd.read_csv('data/transactions.csv')

df_dict = {
    'campaigns' : campaigns_df, 
    'customers' : customers_df, 
    'events' : events_df,
    'products' : products_df,
    'transactions' : transactions_df
}

In [4]:
for name, df in df_dict.items() : 
    print(f'========= {name} ==========')
    df.info()

========= campaigns ==========
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   campaign_id      50 non-null     int64
 1   channel          50 non-null     str
 2   objective        50 non-null     str
 3   start_date       50 non-null     str
 4   end_date         50 non-null     str
 5   target_segment   50 non-null     str
 6   expected_uplift  50 non-null     float64
dtypes: float64(1), int64(1), str(5)
memory usage: 2.9 KB
========= customers ==========
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          100000 non-null  int64
 1   signup_date          100000 non-null  str
 2   country              100000 non-null  str
 3   age                  100000 non-null  int64
 4   gender               100000 non-null  str
 5   loyalty_tier         100000 non-null  str
 6   acquisition_channel  100000 non-null  str
dtypes: int64(2), str(5)
memory usage: 5.3 MB
========= events ==========
<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             str
 2   customer_id           int64
 3   session_id            int64
 4   event_type            str
 5   product_id            float64
 6   device_type           str
 7   traffic_source        str
 8   campaign_id           int64
 9   page_category         str
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: float64(2), int64(4), str(6)
memory usage: 183.1 MB
========= products ==========
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   str
 2   brand        2000 non-null   str
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   str
 5   is_premium   2000 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 93.9 KB
========= transactions ==========
<class 'pandas.DataFrame'>
RangeIndex: 103127 entries, 0 to 103126
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    103127 non-null  int64
 1   timestamp         103127 non-null  str
 2   customer_id       103127 non-null  int64
 3   product_id        92678 non-null   float64
 4   quantity          103127 non-null  int64
 5   discount_applied  103127 non-null  float64
 6   gross_revenue     92678 non-null   float64
 7   campaign_id       103127 non-null  int64
 8   refund_flag       103127 non-null  int64
dtypes: float64(3), int64(5), str(1)
memory usage: 7.1 MB

**Insight**
- Terdapat kolom date yang masih belum sesuai tipe datanya
- Terdapat data yang kosong pada tabel transactions

In [5]:
for name,df in df_dict.items() : 
    print(f'============ {name} ==============')
    print(df.describe(include='all'))

============ campaigns ==============
        campaign_id      channel     objective  start_date    end_date  \
count      50.00000           50            50          50          50
unique          NaN            5             4          49          48
top             NaN  Paid Search  Reactivation  2022-07-25  2022-09-29
freq            NaN           11            15           2           2
mean       25.50000          NaN           NaN         NaN         NaN
std        14.57738          NaN           NaN         NaN         NaN
min         1.00000          NaN           NaN         NaN         NaN
25%        13.25000          NaN           NaN         NaN         NaN
50%        25.50000          NaN           NaN         NaN         NaN
75%        37.75000          NaN           NaN         NaN         NaN
max        50.00000          NaN           NaN         NaN         NaN

       target_segment  expected_uplift
count              50        50.000000
unique              5              NaN
top     New Customers              NaN
freq               12              NaN
mean              NaN         0.086660
std               NaN         0.035854
min               NaN         0.022000
25%               NaN         0.057250
50%               NaN         0.092500
75%               NaN         0.113750
max               NaN         0.144000
============ customers ==============
          customer_id signup_date country            age  gender loyalty_tier  \
count   100000.000000      100000  100000  100000.000000  100000       100000
unique            NaN        1095       7            NaN       3            4
top               NaN  2022-11-04      US            NaN    Male       Bronze
freq              NaN         124   34931            NaN   48054        60276
mean     50000.500000         NaN     NaN      35.224370     NaN          NaN
std      28867.657797         NaN     NaN       9.595792     NaN          NaN
min          1.000000         NaN     NaN      18.000000     NaN          NaN
25%      25000.750000         NaN     NaN      28.000000     NaN          NaN
50%      50000.500000         NaN     NaN      35.000000     NaN          NaN
75%      75000.250000         NaN     NaN      42.000000     NaN          NaN
max     100000.000000         NaN     NaN      70.000000     NaN          NaN

       acquisition_channel
count               100000
unique                   5
top                Organic
freq                 30200
mean                   NaN
std                    NaN
min                    NaN
25%                    NaN
50%                    NaN
75%                    NaN
max                    NaN
============ events ==============
            event_id            timestamp   customer_id    session_id  \
count   2.000000e+06              2000000  2.000000e+06  2.000000e+06
unique           NaN              1977065           NaN           NaN
top              NaN  2023-09-18 07:00:22           NaN           NaN
freq             NaN                    4           NaN           NaN
mean    1.000000e+06                  NaN  5.001209e+04  3.330514e+05
std     5.773504e+05                  NaN  2.887960e+04  1.924715e+05
min     1.000000e+00                  NaN  1.000000e+00  1.000000e+00
25%     5.000008e+05                  NaN  2.501000e+04  1.662308e+05
50%     1.000000e+06                  NaN  5.000900e+04  3.328190e+05
75%     1.500000e+06                  NaN  7.503800e+04  4.997712e+05
max     2.000000e+06                  NaN  1.000000e+05  6.666660e+05

       event_type    product_id device_type traffic_source   campaign_id  \
count     2000000  1.799629e+06     1959700        2000000  2.000000e+06
unique          5           NaN           3             10           NaN
top          view           NaN      mobile        Organic           NaN
freq      1043573           NaN     1176146         776758           NaN
mean          NaN  1.000100e+03         NaN            NaN  1.276203e+01
std           NaN  5.776716e+02         NaN            NaN  1.634052e+01
min           NaN  1.000000e+00         NaN            NaN  0.000000e+00
25%           NaN  5.000000e+02         NaN            NaN  0.000000e+00
50%           NaN  1.000000e+03         NaN            NaN  0.000000e+00
75%           NaN  1.501000e+03         NaN            NaN  2.600000e+01
max           NaN  2.000000e+03         NaN            NaN  5.000000e+01

       page_category  session_duration_sec experiment_group
count        2000000          2.000000e+06          2000000
unique             5                   NaN                3
top              PLP                   NaN          Control
freq          601284                   NaN          1198404
mean             NaN          1.306426e+02              NaN
std              NaN          1.590376e+02              NaN
min              NaN          1.000000e-01              NaN
25%              NaN          5.810000e+01              NaN
50%              NaN          1.017000e+02              NaN
75%              NaN          1.640000e+02              NaN
max              NaN          7.533800e+03              NaN
============ products ==============
         product_id     category    brand   base_price launch_date  \
count   2000.000000         2000     2000  2000.000000        2000
unique          NaN            6      100          NaN         901
top             NaN  Electronics  Brand_7          NaN  2021-01-18
freq            NaN          455       32          NaN           7
mean    1000.500000          NaN      NaN    72.166650         NaN
std      577.494589          NaN      NaN    52.315792         NaN
min        1.000000          NaN      NaN     5.110000         NaN
25%      500.750000          NaN      NaN    32.505000         NaN
50%     1000.500000          NaN      NaN    61.245000         NaN
75%     1500.250000          NaN      NaN    97.955000         NaN
max     2000.000000          NaN      NaN   464.580000         NaN

         is_premium
count   2000.000000
unique          NaN
top             NaN
freq            NaN
mean       0.500000
std        0.500125
min        0.000000
25%        0.000000
50%        0.500000
75%        1.000000
max        1.000000
============ transactions ==============
        transaction_id            timestamp    customer_id   product_id  \
count    103127.000000               103127  103127.000000  92678.00000
unique             NaN               103074            NaN          NaN
top                NaN  2022-11-06 18:59:39            NaN          NaN
freq               NaN                    2            NaN          NaN
mean      51564.000000                  NaN   49946.662707    999.63139
std       29770.344943                  NaN   28841.644812    576.19187
min           1.000000                  NaN       2.000000      1.00000
25%       25782.500000                  NaN   25081.000000    498.00000
50%       51564.000000                  NaN   49957.000000   1002.00000
75%       77345.500000                  NaN   74870.500000   1498.00000
max      103127.000000                  NaN  100000.000000   2000.00000

             quantity  discount_applied  gross_revenue    campaign_id  \
count   103127.000000     103127.000000   92678.000000  103127.000000
unique            NaN               NaN            NaN            NaN
top               NaN               NaN            NaN            NaN
freq              NaN               NaN            NaN            NaN
mean         1.381539          0.041379      90.355493      19.945252
std          0.748176          0.060286     100.684683      16.379672
min          1.000000          0.000000    -783.040000       0.000000
25%          1.000000          0.000000      34.240000       4.000000
50%          1.000000          0.000000      68.000000      18.000000
75%          1.000000          0.050000     117.617500      34.000000
max          4.000000          0.200000    1858.320000      50.000000

          refund_flag
count   103127.000000
unique            NaN
top               NaN
freq              NaN
mean         0.029372
std          0.168846
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000

Insight : 
- Campaign yang dilakukan lebih banyak dengan tujuan reactivation, melalui saluran paid search, dan dengan target segment new customer
- Customer yang melakukan sign up, customer lebih banyak tier bronze, yang berasal dari saluran organic, dan rata rata usia 35
- Customer yang menggunakan website, banyak melihat dan customer menggunakan mobile, dengan rata rata sesi durasi 1.3s 
- Product yang dijual, kebanyakan electronic dan brand Brand_7, rata rata product yang dijual dengahan harga kurang lebih 72
- transaksi dengan rata rata total produk yang terjual 1 dan revenue yang didapatkan rata rata 90

In [6]:
for name, df in df_dict.items() : 
    print(f'====== {name} ======')
    for col in df.select_dtypes(include=['object', 'str', 'category']).columns : 
        print(f'====== {col} ======')
        print(df[col].unique())

====== campaigns ======
====== channel ======
<StringArray>
['Paid Search', 'Email', 'Display', 'Social', 'Affiliate']
Length: 5, dtype: str
====== objective ======
<StringArray>
['Cross-sell', 'Retention', 'Reactivation', 'Acquisition']
Length: 4, dtype: str
====== start_date ======
<StringArray>
['2021-10-25', '2021-10-24', '2023-10-08', '2022-07-25', '2022-07-09',
 '2021-10-20', '2023-07-02', '2021-08-23', '2023-10-09', '2022-09-01',
 '2022-11-02', '2021-01-20', '2022-03-19', '2022-09-20', '2022-04-29',
 '2023-08-10', '2023-04-05', '2022-10-09', '2021-11-28', '2021-07-26',
 '2023-02-21', '2022-07-02', '2022-10-25', '2021-11-07', '2021-03-19',
 '2023-08-13', '2022-04-01', '2021-09-02', '2021-12-26', '2023-11-04',
 '2023-10-26', '2021-08-05', '2022-02-15', '2023-03-19', '2022-11-06',
 '2023-04-03', '2022-10-20', '2021-12-18', '2023-03-08', '2023-04-09',
 '2023-04-22', '2023-03-12', '2021-01-31', '2022-04-08', '2023-03-23',
 '2022-04-12', '2022-01-05', '2021-04-09', '2021-02-14']
Length: 49, dtype: str
====== end_date ======
<StringArray>
['2021-11-26', '2021-12-24', '2023-11-30', '2022-10-07', '2022-09-29',
 '2021-12-03', '2023-08-10', '2021-09-30', '2023-12-30', '2022-10-22',
 '2023-01-14', '2021-02-21', '2022-06-09', '2022-05-10', '2023-10-15',
 '2023-04-24', '2022-12-07', '2022-01-29', '2021-09-23', '2023-03-27',
 '2022-09-18', '2023-01-19', '2022-01-06', '2021-04-11', '2023-11-01',
 '2022-04-11', '2021-09-11', '2022-02-26', '2024-01-06', '2023-12-03',
 '2021-10-16', '2022-04-18', '2023-05-13', '2022-11-26', '2023-06-10',
 '2022-12-01', '2022-01-31', '2023-05-11', '2022-09-07', '2023-04-17',
 '2023-06-29', '2023-04-18', '2021-04-17', '2022-06-15', '2022-06-04',
 '2022-04-04', '2021-05-24', '2021-03-24']
Length: 48, dtype: str
====== target_segment ======
<StringArray>
['Deal Seekers', 'Churn Risk', 'New Customers', 'High Value', 'All']
Length: 5, dtype: str
====== customers ======
====== signup_date ======
<StringArray>
['2021-04-08', '2023-04-28', '2022-12-18', '2022-04-26', '2022-04-20',
 '2023-07-30', '2021-04-05', '2023-02-03', '2021-08-09', '2021-04-14',
 ...
 '2022-11-15', '2022-01-23', '2021-01-15', '2023-02-01', '2023-10-20',
 '2022-06-16', '2022-01-26', '2021-05-01', '2022-06-15', '2023-09-18']
Length: 1095, dtype: str
====== country ======
<StringArray>
['BR', 'IN', 'UK', 'US', 'CA', 'AU', 'DE']
Length: 7, dtype: str
====== gender ======
<StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
====== loyalty_tier ======
<StringArray>
['Bronze', 'Silver', 'Gold', 'Platinum']
Length: 4, dtype: str
====== acquisition_channel ======
<StringArray>
['Referral', 'Organic', 'Paid Search', 'Social', 'Email']
Length: 5, dtype: str
====== events ======
====== timestamp ======
<StringArray>
['2021-01-14 13:35:43', '2021-12-03 21:36:50', '2021-12-27 08:25:15',
 '2022-01-22 15:06:54', '2021-05-10 12:03:09', '2022-03-04 11:41:45',
 '2021-01-27 10:17:26', '2023-07-29 00:49:05', '2023-06-06 21:14:26',
 '2023-05-30 05:56:14',
 ...
 '2021-03-31 10:49:41', '2022-03-23 14:39:23', '2022-11-02 17:15:32',
 '2022-05-05 19:29:04', '2023-02-23 22:53:25', '2023-04-11 18:35:25',
 '2023-01-12 14:54:08', '2022-03-20 12:21:23', '2022-11-19 00:43:28',
 '2021-12-20 05:39:31']
Length: 1977065, dtype: str
====== event_type ======
<StringArray>
['view', 'add_to_cart', 'purchase', 'bounce', 'click']
Length: 5, dtype: str
====== device_type ======
<StringArray>
['desktop', 'mobile', 'tablet', nan]
Length: 4, dtype: str
====== traffic_source ======
<StringArray>
[      'Email',     'Organic', 'Paid Search',      'Social',      'Direct',
 'PAID SEARCH',      'DIRECT',       'EMAIL',     'ORGANIC',      'SOCIAL']
Length: 10, dtype: str
====== page_category ======
<StringArray>
['PLP', 'PDP', 'Checkout', 'Home', 'Cart']
Length: 5, dtype: str
====== experiment_group ======
<StringArray>
['Control', 'Variant_A', 'Variant_B']
Length: 3, dtype: str
====== products ======
====== category ======
<StringArray>
['Grocery', 'Fashion', 'Electronics', 'Sports', 'Beauty', 'Home']
Length: 6, dtype: str
====== brand ======
<StringArray>
[ 'Brand_58',   'Brand_1',  'Brand_70',  'Brand_56',  'Brand_39',  'Brand_42',
  'Brand_41',  'Brand_73',  'Brand_61',   'Brand_8',  'Brand_20',  'Brand_57',
  'Brand_88',  'Brand_28',  'Brand_75',  'Brand_49',  'Brand_81',  'Brand_16',
  'Brand_67',  'Brand_62',   'Brand_9',   'Brand_2',   'Brand_4',  'Brand_25',
  'Brand_47',  'Brand_78',  'Brand_35',  'Brand_95',  'Brand_37',  'Brand_19',
  'Brand_27',  'Brand_12',  'Brand_23',   'Brand_5',  'Brand_72',  'Brand_18',
  'Brand_14',  'Brand_34',  'Brand_60',  'Brand_26',  'Brand_76',  'Brand_98',
  'Brand_90',  'Brand_91',  'Brand_83',  'Brand_86',  'Brand_94',  'Brand_84',
  'Brand_36',  'Brand_59',  'Brand_87',  'Brand_79',  'Brand_93',  'Brand_44',
  'Brand_52',  'Brand_51',  'Brand_24',   'Brand_6',   'Brand_7',  'Brand_68',
  'Brand_69',  'Brand_74',  'Brand_97',  'Brand_99',  'Brand_10',  'Brand_38',
  'Brand_43',  'Brand_48',  'Brand_22',  'Brand_13',  'Brand_77',  'Brand_96',
   'Brand_3',  'Brand_92',  'Brand_54',  'Brand_89',  'Brand_29',  'Brand_80',
 'Brand_100',  'Brand_64',  'Brand_31',  'Brand_50',  'Brand_30',  'Brand_82',
  'Brand_71',  'Brand_65',  'Brand_45',  'Brand_40',  'Brand_53',  'Brand_63',
  'Brand_17',  'Brand_33',  'Brand_21',  'Brand_46',  'Brand_15',  'Brand_55',
  'Brand_32',  'Brand_85',  'Brand_66',  'Brand_11']
Length: 100, dtype: str
====== launch_date ======
<StringArray>
['2021-08-02', '2021-09-14', '2021-01-18', '2023-03-03', '2022-04-19',
 '2023-09-16', '2023-05-17', '2021-02-16', '2023-03-11', '2022-08-21',
 ...
 '2022-10-19', '2022-06-07', '2022-01-14', '2023-06-13', '2022-06-29',
 '2023-12-19', '2021-02-22', '2021-01-07', '2023-05-25', '2022-08-25']
Length: 901, dtype: str
====== transactions ======
====== timestamp ======
<StringArray>
['2021-12-27 08:25:15', '2023-06-06 21:14:26', '2023-08-31 05:29:54',
 '2022-06-26 20:33:46', '2023-07-26 18:12:35', '2023-01-19 14:05:58',
 '2023-07-28 09:37:53', '2022-07-10 07:29:15', '2023-11-02 05:22:44',
 '2021-01-25 06:28:42',
 ...
 '2023-11-22 16:20:02', '2021-07-30 15:04:22', '2022-10-04 19:16:49',
 '2023-12-15 12:03:59', '2023-07-28 11:29:49', '2023-12-28 00:33:47',
 '2022-08-03 20:54:47', '2023-08-27 19:39:51', '2022-12-22 22:25:06',
 '2021-12-10 15:00:12']
Length: 103074, dtype: str

**Insight :** 
- Terdapat data yang bias dimana nilainya sama tetapi berbeda letter case pada kolom traffic_source di tabel events
- Terdapat letter case dan tanda '_' akan dibersihkan agar lebih rapi ketika report/visualisasi

## Data Cleaning 
- ganti tipe data tanggal dari str menjadi tipe datetime 
- mengubah data menjadi konsisten (mengubah huruf menjadi proper case, menghilangkan tanda _,angka di belakang koma, sorting datetime data)
- handling missing values

In [7]:
#rounding
campaigns_df['expected_uplift'] = campaigns_df['expected_uplift'].round(2)

In [8]:
#changing data to title case
events_df['traffic_source'] = events_df['traffic_source'].str.title()
events_df['device_type'] = events_df['device_type'].str.title()
events_df['event_type'] = events_df['event_type'].str.replace('_', ' ').str.title()
events_df['experiment_group'] = events_df['experiment_group'].str.replace('_', ' ').str.title()

In [9]:
unknown_data = pd.DataFrame({
    'product_id' : [0], 
    'category' : ['Unknown'], 
    'brand' : ['Unknown'], 
    'base_price' : ['Unknown'], 
    'launch_date' : [np.nan],
    'is_premium': ['Unknown']
})

products_df = pd.concat([products_df, unknown_data], 
          ignore_index=True)

In [10]:
#handling missing values
transactions_df['product_id'] = transactions_df['product_id'].fillna(0).astype(int)
transactions_df['gross_revenue'] = transactions_df['gross_revenue'].fillna(0)

In [11]:
events_df['product_id'] = events_df['product_id'].fillna(0).astype(int)

In [12]:
events_df.iloc[events_df['page_category'] == 'Bounce']

Empty DataFrame
Columns: [event_id, timestamp, customer_id, session_id, event_type, product_id, device_type, traffic_source, campaign_id, page_category, session_duration_sec, experiment_group]
Index: []

In [13]:
events_df.isnull().sum()

event_id                    0
timestamp                   0
customer_id                 0
session_id                  0
event_type                  0
product_id                  0
device_type             40300
traffic_source              0
campaign_id                 0
page_category               0
session_duration_sec        0
experiment_group            0
dtype: int64

In [14]:
products_df['launch_date']

0       2021-08-02
1       2021-09-14
2       2021-01-18
3       2023-03-03
4       2022-04-19
           ...
1996    2022-06-19
1997    2021-10-21
1998    2023-08-11
1999    2021-01-15
2000           NaN
Name: launch_date, Length: 2001, dtype: object

In [15]:
#changing to datetime type 
campaigns_df['start_date'] = pd.to_datetime(campaigns_df['start_date'])
campaigns_df['end_date'] = pd.to_datetime(campaigns_df['end_date'])
events_df['timestamp'] = pd.to_datetime(events_df['timestamp'])
products_df['launch_date'] = pd.to_datetime(products_df['launch_date'])
customers_df['signup_date'] = pd.to_datetime(customers_df['signup_date'])
transactions_df['timestamp'] = pd.to_datetime(transactions_df['timestamp'])

In [16]:
events_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             datetime64[us]
 2   customer_id           int64
 3   session_id            int64
 4   event_type            str
 5   product_id            int64
 6   device_type           str
 7   traffic_source        str
 8   campaign_id           int64
 9   page_category         str
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: datetime64[us](1), float64(1), int64(5), str(5)
memory usage: 183.1 MB

In [17]:
events_df.iloc[events_df['page_category'] == 'bounce']

Empty DataFrame
Columns: [event_id, timestamp, customer_id, session_id, event_type, product_id, device_type, traffic_source, campaign_id, page_category, session_duration_sec, experiment_group]
Index: []

In [18]:
#total missing values 
transactions_df.isnull().sum()

transaction_id      0
timestamp           0
customer_id         0
product_id          0
quantity            0
discount_applied    0
gross_revenue       0
campaign_id         0
refund_flag         0
dtype: int64

In [19]:
transactions_df.iloc[transactions_df['product_id'].isna()]

Empty DataFrame
Columns: [transaction_id, timestamp, customer_id, product_id, quantity, discount_applied, gross_revenue, campaign_id, refund_flag]
Index: []

In [20]:
events_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             datetime64[us]
 2   customer_id           int64
 3   session_id            int64
 4   event_type            str
 5   product_id            int64
 6   device_type           str
 7   traffic_source        str
 8   campaign_id           int64
 9   page_category         str
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: datetime64[us](1), float64(1), int64(5), str(5)
memory usage: 183.1 MB

In [21]:
df_dict = {
    'dim_campaigns' : campaigns_df, 
    'dim_customers' : customers_df, 
    'fact_events' : events_df,
    'dim_products' : products_df,
    'fact_transactions' : transactions_df
}

### Integrate to Database

In [22]:
#connecting local database
server = 'LAPTOP-QOFMN6O5\SQLEXPRESS'
database = 'e_commerce_customer_and_marketing_analytics'
driver = 'ODBC Driver 17 for SQL Server'


connection_url = URL.create(
    "mssql+pyodbc", 
    query={
        "odbc_connect" : (
            f"DRIVER={{{driver}}};"
            f"SERVER={server};"
            f"DATABASE={database};"
            "Trusted_Connection=yes;"
        )
    }
)

#create engine for connection
engine = create_engine(connection_url)

In [23]:
with engine.connect() as conn : 
    print('tes')

tes

In [24]:
#load dataset to local database
for table_name, df in df_dict.items() : 
    df.to_sql(
        name= table_name, 
        con= engine,
        schema='dbo', 
        if_exists = 'replace', 
        index=False,
    )

In [25]:
customers_df

,customer_id,signup_date,country,age,gender,loyalty_tier,acquisition_channel
0,1,2021-04-08,BR,48,Male,Bronze,Referral
1,2,2023-04-28,IN,36,Female,Silver,Organic
2,3,2022-12-18,UK,35,Female,Silver,Organic
3,4,2022-04-26,US,45,Male,Silver,Paid Search
4,5,2022-04-20,IN,53,Male,Silver,Organic
...,...,...,...,...,...,...,...
99995,99996,2023-12-16,US,46,Male,Bronze,Paid Search
99996,99997,2021-01-20,IN,37,Male,Bronze,Organic
99997,99998,2022-09-22,US,38,Female,Bronze,Social
99998,99999,2021-01-06,IN,19,Female,Silver,Email
99999,100000,2023-10-24,CA,39,Female,Gold,Email

# TO DO
- menyamakan tipe data product_id di fact tabel dengan dim tabel agar dapat dijoin
- pass data cleaning ke database 
- analisis customer sql

In [26]:
#